import type { ProjectDataType } from "./index";

export const Example_Issues_2: ProjectDataType[] = [
  {
    id: "51",
    name: "AI-Powered Customer Service",
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-01-31"),
    projectKey: "AI-CS-051",
    status: "high",
    progress: 65,
    team: "engineering",
    priority: "high",
    category: "Revolutionize Customer Experience",
    riskLevel: "high"
  },
  {
    id: "52",
    name: "Sustainable Packaging Initiative",
    startDate: new Date("2024-02-01"),
    endDate: new Date("2024-02-29"),
    projectKey: "SUSTAIN-052",
    status: "low",
    progress: 20,
    team: "product",
    priority: "high",
    category: "The Consistancy of Axiom of Choice and General Continuum Hypothesis in the Context of Set Theory",
    riskLevel: "low"
  },
  {
    id: "53",
    name: "Mobile App Redesign",
    startDate: new Date("2024-03-01"),
    endDate: new Date("2024-03-31"),
    projectKey: "MOBILE-053",
    status: "medium",
    progress: 45,
    team: "engineering",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "54",
    name: "Global Supply Chain Optimization",
    startDate: new Date("2024-04-01"),
    endDate: new Date("2024-04-30"),
    projectKey: "SUPPLY-054",
    status: "medium",
    progress: 30,
    team: "other",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "55",
    name: "Employee Training Platform",
    startDate: new Date("2024-05-01"),
    endDate: new Date("2024-05-31"),
    projectKey: "TRAIN-055",
    status: "medium",
    progress: 100,
    team: "other",
    priority: "low",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "56",
    name: "Data Security Enhancement",
    startDate: new Date("2024-06-01"),
    endDate: new Date("2024-06-30"),
    projectKey: "SEC-056",
    status: "high",
    progress: 75,
    team: "engineering",
    priority: "low",
    category: "Evolving Cyber Threats",
    riskLevel: "high"
  },
  {
    id: "57",
    name: "Retail Store Digitalization",
    startDate: new Date("2024-07-01"),
    endDate: new Date("2024-07-31"),
    projectKey: "RETAIL-057",
    status: "low",
    progress: 100,
    team: "other",
    priority: "low",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "58",
    name: "E-commerce Platform Upgrade",
    startDate: new Date("2024-08-01"),
    endDate: new Date("2024-08-31"),
    projectKey: "ECOM-058",
    status: "medium",
    progress: 60,
    team: "engineering",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "59",
    name: "Brand Identity Refresh",
    startDate: new Date("2024-09-01"),
    endDate: new Date("2024-09-30"),
    projectKey: "BRAND-059",
    status: "low",
    progress: 25,
    team: "marketing",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "60",
    name: "Corporate Social Responsibility",
    startDate: new Date("2024-10-01"),
    endDate: new Date("2024-10-31"),
    projectKey: "CSR-060",
    status: "medium",
    progress: 40,
    team: "other",
    priority: "medium",
    category: "Advance Capabilities",
    riskLevel: "medium"
  },
  {
    id: "61",
    name: "Product Innovation Lab",
    startDate: new Date("2024-11-01"),
    endDate: new Date("2024-11-30"),
    projectKey: "INNOV-061",
    status: "low",
    progress: 10,
    team: "product",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "62",
    name: "Customer Analytics Platform",
    startDate: new Date("2024-12-01"),
    endDate: new Date("2024-12-31"),
    projectKey: "ANALYTICS-062",
    status: "medium",
    progress: 55,
    team: "engineering",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "63",
    name: "Global Market Expansion",
    startDate: new Date("2025-01-01"),
    endDate: new Date("2025-01-31"),
    projectKey: "GLOBAL-063",
    status: "low",
    progress: 20,
    team: "other",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "64",
    name: "Smart Inventory System",
    startDate: new Date("2025-02-01"),
    endDate: new Date("2025-02-28"),
    projectKey: "INVENTORY-064",
    status: "medium",
    progress: 70,
    team: "other",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "65",
    name: "Digital Marketing Campaign",
    startDate: new Date("2025-03-01"),
    endDate: new Date("2025-03-31"),
    projectKey: "MARKETING-065",
    status: "low",
    progress: 35,
    team: "marketing",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "66",
    name: "Employee Wellness Program",
    startDate: new Date("2025-04-01"),
    endDate: new Date("2025-04-30"),
    projectKey: "WELLNESS-066",
    status: "medium",
    progress: 45,
    team: "other",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "67",
    name: "Store Experience Redesign",
    startDate: new Date("2025-05-01"),
    endDate: new Date("2025-05-31"),
    projectKey: "STORE-067",
    status: "low",
    progress: 100,
    team: "other",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "68",
    name: "Cloud Infrastructure Migration",
    startDate: new Date("2025-06-01"),
    endDate: new Date("2025-06-30"),
    projectKey: "CLOUD-068",
    status: "high",
    progress: 60,
    team: "engineering",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "high"
  },
  {
    id: "69",
    name: "Product Quality Enhancement",
    startDate: new Date("2025-07-01"),
    endDate: new Date("2025-07-31"),
    projectKey: "QUALITY-069",
    status: "low",
    progress: 25,
    team: "product",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "70",
    name: "E-commerce Analytics Dashboard",
    startDate: new Date("2025-08-01"),
    endDate: new Date("2025-08-31"),
    projectKey: "DASH-070",
    status: "medium",
    progress: 50,
    team: "engineering",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "71",
    name: "Corporate Sustainability Goals",
    startDate: new Date("2025-09-01"),
    endDate: new Date("2025-09-30"),
    projectKey: "SUSTAIN-071",
    status: "low",
    progress: 30,
    team: "other",
    priority: "medium",
    category: "Advance Capabilities",
    riskLevel: "low"
  },
  {
    id: "72",
    name: "Employee Training Program",
    startDate: new Date("2025-10-01"),
    endDate: new Date("2025-10-31"),
    projectKey: "TRAIN-072",
    status: "medium",
    progress: 40,
    team: "other",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "73",
    name: "Retail Technology Integration",
    startDate: new Date("2025-11-01"),
    endDate: new Date("2025-11-30"),
    projectKey: "TECH-073",
    status: "low",
    progress: 20,
    team: "other",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "74",
    name: "Brand Awareness Campaign",
    startDate: new Date("2025-12-01"),
    endDate: new Date("2025-12-31"),
    projectKey: "BRAND-074",
    status: "medium",
    progress: 35,
    team: "marketing",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "75",
    name: "Supply Chain Visibility",
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-01-31"),
    projectKey: "SUPPLY-075",
    status: "low",
    progress: 25,
    team: "other",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "76",
    name: "AI Product Recommendations",
    startDate: new Date("2024-02-01"),
    endDate: new Date("2024-02-29"),
    projectKey: "AI-076",
    status: "medium",
    progress: 55,
    team: "engineering",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "77",
    name: "Store Performance Metrics",
    startDate: new Date("2024-03-01"),
    endDate: new Date("2024-03-31"),
    projectKey: "METRICS-077",
    status: "low",
    progress: 30,
    team: "other",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "78",
    name: "E-commerce Mobile App",
    startDate: new Date("2024-04-01"),
    endDate: new Date("2024-04-30"),
    projectKey: "MOBILE-078",
    status: "medium",
    progress: 65,
    team: "engineering",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "79",
    name: "Brand Voice Guidelines",
    startDate: new Date("2024-05-01"),
    endDate: new Date("2024-05-31"),
    projectKey: "VOICE-079",
    status: "low",
    progress: 40,
    team: "marketing",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "80",
    name: "Corporate Ethics Program",
    startDate: new Date("2024-06-01"),
    endDate: new Date("2024-06-30"),
    projectKey: "ETHICS-080",
    status: "medium",
    progress: 45,
    team: "other",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "81",
    name: "Product Design System",
    startDate: new Date("2024-07-01"),
    endDate: new Date("2024-07-31"),
    projectKey: "DESIGN-081",
    status: "low",
    progress: 35,
    team: "product",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "82",
    name: "HR Management System",
    startDate: new Date("2024-08-01"),
    endDate: new Date("2024-08-31"),
    projectKey: "HR-082",
    status: "medium",
    progress: 60,
    team: "other",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "83",
    name: "Retail Analytics Dashboard",
    startDate: new Date("2024-09-01"),
    endDate: new Date("2024-09-30"),
    projectKey: "RETAIL-083",
    status: "low",
    progress: 25,
    team: "other",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "84",
    name: "Cloud Security Framework",
    startDate: new Date("2024-10-01"),
    endDate: new Date("2024-10-31"),
    projectKey: "SEC-084",
    status: "high",
    progress: 70,
    team: "engineering",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "high"
  },
  {
    id: "85",
    name: "E-commerce Checkout Optimization",
    startDate: new Date("2024-11-01"),
    endDate: new Date("2024-11-30"),
    projectKey: "CHECKOUT-085",
    status: "low",
    progress: 30,
    team: "engineering",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "86",
    name: "Brand Content Strategy",
    startDate: new Date("2024-12-01"),
    endDate: new Date("2024-12-31"),
    projectKey: "CONTENT-086",
    status: "medium",
    progress: 50,
    team: "marketing",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "87",
    name: "Corporate Risk Management",
    startDate: new Date("2025-01-01"),
    endDate: new Date("2025-01-31"),
    projectKey: "RISK-087",
    status: "low",
    progress: 35,
    team: "other",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "88",
    name: "Product Quality Assurance",
    startDate: new Date("2025-02-01"),
    endDate: new Date("2025-02-28"),
    projectKey: "QA-088",
    status: "medium",
    progress: 55,
    team: "product",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "89",
    name: "Employee Performance System",
    startDate: new Date("2025-03-01"),
    endDate: new Date("2025-03-31"),
    projectKey: "PERF-089",
    status: "low",
    progress: 40,
    team: "other",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "90",
    name: "Store Operations Platform",
    startDate: new Date("2025-04-01"),
    endDate: new Date("2025-04-30"),
    projectKey: "OPS-090",
    status: "medium",
    progress: 65,
    team: "other",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "91",
    name: "API Security Enhancement",
    startDate: new Date("2025-05-01"),
    endDate: new Date("2025-05-31"),
    projectKey: "API-091",
    status: "high",
    progress: 45,
    team: "engineering",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "high"
  },
  {
    id: "92",
    name: "E-commerce Search Optimization",
    startDate: new Date("2025-06-01"),
    endDate: new Date("2025-06-30"),
    projectKey: "SEARCH-092",
    status: "medium",
    progress: 50,
    team: "engineering",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "93",
    name: "Brand Experience Platform",
    startDate: new Date("2025-07-01"),
    endDate: new Date("2025-07-31"),
    projectKey: "EXP-093",
    status: "low",
    progress: 30,
    team: "marketing",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "94",
    name: "Corporate Compliance System",
    startDate: new Date("2025-08-01"),
    endDate: new Date("2025-08-31"),
    projectKey: "COMPLY-094",
    status: "medium",
    progress: 60,
    team: "other",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "95",
    name: "Product Innovation Process",
    startDate: new Date("2025-09-01"),
    endDate: new Date("2025-09-30"),
    projectKey: "INNOV-095",
    status: "low",
    progress: 35,
    team: "product",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "96",
    name: "HR Analytics Platform",
    startDate: new Date("2025-10-01"),
    endDate: new Date("2025-10-31"),
    projectKey: "HR-096",
    status: "medium",
    progress: 55,
    team: "other",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "97",
    name: "Retail Customer Insights",
    startDate: new Date("2025-11-01"),
    endDate: new Date("2025-11-30"),
    projectKey: "INSIGHTS-097",
    status: "low",
    progress: 40,
    team: "other",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "98",
    name: "Cloud Migration Strategy",
    startDate: new Date("2025-12-01"),
    endDate: new Date("2025-12-31"),
    projectKey: "MIGRATE-098",
    status: "medium",
    progress: 45,
    team: "engineering",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "99",
    name: "E-commerce Payment System",
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-01-31"),
    projectKey: "PAY-099",
    status: "low",
    progress: 30,
    team: "engineering",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "100",
    name: "Brand Strategy Refresh",
    startDate: new Date("2024-02-01"),
    endDate: new Date("2024-02-29"),
    projectKey: "STRATEGY-100",
    status: "medium",
    progress: 50,
    team: "marketing",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  }
]; 