import type { ProjectDataType } from "./index";

export const Example_Issues_1: ProjectDataType[] = [
  {
    id: "1",
    name: "Interactive Calculus Workshop",
    startDate: new Date("2023-12-16"),
    endDate: new Date("2024-01-24"),
    projectKey: "CALC-001",
    status: "high",
    progress: 50,
    team: "engineering",
    priority: "high",
    category: "Advance Solutions",
    riskLevel: "high"
  },
  {
    id: "2",
    name: "Mobile App Development",
    startDate: new Date("2024-01-25"),
    endDate: new Date("2024-03-31"),
    projectKey: "MOBILE-002",
    status: "low",
    progress: 100,
    team: "engineering",
    priority: "low",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "3",
    name: "Machine Learning Model Training",
    startDate: new Date("2024-03-01"),
    endDate: new Date("2024-03-31"),
    projectKey: "ML-003",
    status: "high",
    progress: 100,
    team: "engineering",
    priority: "low",
    category: "Advance Capabilities",
    riskLevel: "medium"
  },
  {
    id: "4",
    name: "Website Redesign Project",
    startDate: new Date("2024-04-01"),
    endDate: new Date("2024-04-30"),
    projectKey: "WEB-004",
    status: "medium",
    progress: 75,
    team: "design",
    priority: "high",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "5",
    name: "Data Migration Initiative",
    startDate: new Date("2024-05-01"),
    endDate: new Date("2024-05-31"),
    projectKey: "DATA-005",
    status: "high",
    progress: 25,
    team: "engineering",
    priority: "high",
    category: "Advance Solutions",
    riskLevel: "high"
  },
  {
    id: "6",
    name: "Customer Support Automation",
    startDate: new Date("2024-06-01"),
    endDate: new Date("2024-06-30"),
    projectKey: "CS-006",
    status: "high",
    progress: 60,
    team: "product",
    priority: "high",
    category: "Advance Capabilities",
    riskLevel: "low"
  },
  {
    id: "7",
    name: "Blockchain Integration",
    startDate: new Date("2024-07-01"),
    endDate: new Date("2024-08-31"),
    projectKey: "BLOCK-007",
    status: "high",
    progress: 5,
    team: "engineering",
    priority: "high",
    category: "Evolving Cyber Threats",
    riskLevel: "high"
  },
  {
    id: "8",
    name: "IoT Sensor Network",
    startDate: new Date("2024-08-01"),
    endDate: new Date("2024-08-31"),
    projectKey: "IOT-008",
    status: "medium",
    progress: 40,
    team: "engineering",
    priority: "high",
    category: "Advance Capabilities",
    riskLevel: "medium"
  },
  {
    id: "9",
    name: "Cybersecurity Audit",
    startDate: new Date("2024-09-01"),
    endDate: new Date("2024-09-30"),
    projectKey: "SEC-009",
    status: "high",
    progress: 100,
    team: "engineering",
    priority: "high",
    category: "Evolving Cyber Threats",
    riskLevel: "low"
  },
  {
    id: "10",
    name: "Virtual Reality Training Platform",
    startDate: new Date("2024-10-01"),
    endDate: new Date("2024-10-31"),
    projectKey: "VR-010",
    status: "medium",
    progress: 35,
    team: "engineering",
    priority: "high",
    category: "Advance Capabilities",
    riskLevel: "medium"
  },
  {
    id: "11",
    name: "API Gateway Implementation",
    startDate: new Date("2024-11-01"),
    endDate: new Date("2024-11-30"),
    projectKey: "API-011",
    status: "high",
    progress: 85,
    team: "engineering",
    priority: "high",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "12",
    name: "Cloud Migration Strategy",
    startDate: new Date("2024-12-01"),
    endDate: new Date("2024-12-31"),
    projectKey: "CLOUD-012",
    status: "low",
    progress: 10,
    team: "engineering",
    priority: "high",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "13",
    name: "User Authentication System",
    startDate: new Date("2025-01-01"),
    endDate: new Date("2025-01-31"),
    projectKey: "AUTH-013",
    status: "high",
    progress: 65,
    team: "engineering",
    priority: "high",
    category: "Evolving Cyber Threats",
    riskLevel: "high"
  },
  {
    id: "14",
    name: "Analytics Dashboard",
    startDate: new Date("2025-02-01"),
    endDate: new Date("2025-02-28"),
    projectKey: "DASH-014",
    status: "high",
    progress: 100,
    team: "engineering",
    priority: "high",
    category: "Advance Capabilities",
    riskLevel: "low"
  },
  {
    id: "15",
    name: "Automated Testing Framework",
    startDate: new Date("2025-03-01"),
    endDate: new Date("2025-04-30"),
    projectKey: "TEST-015",
    status: "medium",
    progress: 70,
    team: "engineering",
    priority: "high",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "16",
    name: "Digital Twin Development",
    startDate: new Date("2025-05-01"),
    endDate: new Date("2025-05-31"),
    projectKey: "TWIN-016",
    status: "low",
    progress: 5,
    team: "engineering",
    priority: "high",
    category: "Advance Capabilities",
    riskLevel: "high"
  },
  {
    id: "17",
    name: "Supply Chain Optimization",
    startDate: new Date("2025-06-01"),
    endDate: new Date("2025-06-30"),
    projectKey: "SUPPLY-017",
    status: "high",
    progress: 45,
    team: "other",
    priority: "high",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "18",
    name: "Microservices Architecture",
    startDate: new Date("2025-07-01"),
    endDate: new Date("2025-07-31"),
    projectKey: "MICRO-018",
    status: "low",
    progress: 100,
    team: "engineering",
    priority: "high",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "19",
    name: "Edge Computing Infrastructure",
    startDate: new Date("2025-08-01"),
    endDate: new Date("2025-08-31"),
    projectKey: "EDGE-019",
    status: "medium",
    progress: 30,
    team: "engineering",
    priority: "high",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "20",
    name: "Quantum Computing Research",
    startDate: new Date("2025-09-01"),
    endDate: new Date("2025-09-30"),
    projectKey: "QUANTUM-020",
    status: "low",
    progress: 8,
    team: "engineering",
    priority: "high",
    category: "Advance Capabilities",
    riskLevel: "high"
  },
  {
    id: "21",
    name: "Green Energy Management",
    startDate: new Date("2025-10-01"),
    endDate: new Date("2025-11-30"),
    projectKey: "GREEN-021",
    status: "high",
    progress: 55,
    team: "other",
    priority: "high",
    category: "Advance Capabilities",
    riskLevel: "low"
  },
  {
    id: "22",
    name: "Healthcare Data Platform",
    startDate: new Date("2025-12-01"),
    endDate: new Date("2025-12-31"),
    projectKey: "HEALTH-022",
    status: "medium",
    progress: 90,
    team: "engineering",
    priority: "high",
    category: "Data Analysis",
    riskLevel: "medium"
  },
  {
    id: "23",
    name: "Augmented Reality Interface",
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-01-31"),
    projectKey: "AR-023",
    status: "high",
    progress: 25,
    team: "engineering",
    priority: "high",
    category: "Advance Capabilities",
    riskLevel: "low"
  },
  {
    id: "24",
    name: "Natural Language Processing",
    startDate: new Date("2024-02-01"),
    endDate: new Date("2024-02-29"),
    projectKey: "NLP-024",
    status: "high",
    progress: 100,
    team: "engineering",
    priority: "high",
    category: "Advance Capabilities",
    riskLevel: "low"
  },
  {
    id: "25",
    name: "Robotic Process Automation",
    startDate: new Date("2024-03-01"),
    endDate: new Date("2024-03-31"),
    projectKey: "RPA-025",
    status: "medium",
    progress: 50,
    team: "engineering",
    priority: "high",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "26",
    name: "5G Network Integration",
    startDate: new Date("2024-04-01"),
    endDate: new Date("2024-04-30"),
    projectKey: "5G-026",
    status: "low",
    progress: 12,
    team: "engineering",
    priority: "high",
    category: "Advance Solutions",
    riskLevel: "high"
  },
  {
    id: "27",
    name: "Digital Identity Platform",
    startDate: new Date("2024-05-01"),
    endDate: new Date("2024-05-31"),
    projectKey: "IDENTITY-027",
    status: "high",
    progress: 40,
    team: "engineering",
    priority: "high",
    category: "Evolving Cyber Threats",
    riskLevel: "high"
  },
  {
    id: "28",
    name: "Computer Vision System",
    startDate: new Date("2024-06-01"),
    endDate: new Date("2024-06-30"),
    projectKey: "VISION-028",
    status: "medium",
    progress: 80,
    team: "engineering",
    priority: "high",
    category: "Advance Capabilities",
    riskLevel: "medium"
  },
  {
    id: "29",
    name: "Smart City Infrastructure",
    startDate: new Date("2024-07-01"),
    endDate: new Date("2024-07-31"),
    projectKey: "SMART-029",
    status: "low",
    progress: 100,
    team: "other",
    priority: "high",
    category: "Advance Capabilities",
    riskLevel: "low"
  },
  {
    id: "30",
    name: "Predictive Analytics Engine",
    startDate: new Date("2024-08-01"),
    endDate: new Date("2024-08-31"),
    projectKey: "PREDICT-030",
    status: "high",
    progress: 60,
    team: "engineering",
    priority: "high",
    category: "Advance Capabilities",
    riskLevel: "low"
  },
  {
    id: "31",
    name: "Voice Recognition System",
    startDate: new Date("2024-09-01"),
    endDate: new Date("2024-09-30"),
    projectKey: "VOICE-031",
    status: "high",
    progress: 100,
    team: "engineering",
    priority: "high",
    category: "Advance Capabilities",
    riskLevel: "low"
  },
  {
    id: "32",
    name: "Distributed Database System",
    startDate: new Date("2024-10-01"),
    endDate: new Date("2024-10-31"),
    projectKey: "DB-032",
    status: "medium",
    progress: 35,
    team: "engineering",
    priority: "high",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "33",
    name: "Drone Delivery Network",
    startDate: new Date("2024-11-01"),
    endDate: new Date("2024-11-30"),
    projectKey: "DRONE-033",
    status: "low",
    progress: 8,
    team: "other",
    priority: "high",
    category: "Advance Solutions",
    riskLevel: "high"
  },
  {
    id: "34",
    name: "Facial Recognition Security",
    startDate: new Date("2024-12-01"),
    endDate: new Date("2024-12-31"),
    projectKey: "FACE-034",
    status: "medium",
    progress: 85,
    team: "engineering",
    priority: "high",
    category: "Evolving Cyber Threats",
    riskLevel: "medium"
  },
  {
    id: "35",
    name: "Environmental Monitoring",
    startDate: new Date("2025-01-01"),
    endDate: new Date("2025-01-31"),
    projectKey: "ENV-035",
    status: "high",
    progress: 45,
    team: "other",
    priority: "high",
    category: "Advance Capabilities",
    riskLevel: "low"
  },
  {
    id: "36",
    name: "Automated Code Generation",
    startDate: new Date("2025-02-01"),
    endDate: new Date("2025-02-28"),
    projectKey: "CODEGEN-036",
    status: "low",
    progress: 100,
    team: "engineering",
    priority: "high",
    category: "Advance Capabilities",
    riskLevel: "medium"
  },
  {
    id: "37",
    name: "Smart Grid Integration",
    startDate: new Date("2025-03-01"),
    endDate: new Date("2025-03-31"),
    projectKey: "GRID-037",
    status: "high",
    progress: 25,
    team: "other",
    priority: "high",
    category: "Advance Capabilities",
    riskLevel: "low"
  },
  {
    id: "38",
    name: "Biometric Payment System",
    startDate: new Date("2025-04-01"),
    endDate: new Date("2025-04-30"),
    projectKey: "BIO-038",
    status: "low",
    progress: 100,
    team: "engineering",
    priority: "high",
    category: "Evolving Cyber Threats",
    riskLevel: "medium"
  },
  {
    id: "39",
    name: "Real-time Translation",
    startDate: new Date("2025-05-01"),
    endDate: new Date("2025-06-30"),
    projectKey: "TRANS-039",
    status: "medium",
    progress: 70,
    team: "engineering",
    priority: "high",
    category: "Advance Capabilities",
    riskLevel: "medium"
  },
  {
    id: "40",
    name: "Autonomous Vehicle Platform",
    startDate: new Date("2025-07-01"),
    endDate: new Date("2025-07-31"),
    projectKey: "AUTO-040",
    status: "low",
    progress: 100,
    team: "engineering",
    priority: "high",
    category: "Advance Capabilities",
    riskLevel: "high"
  },
  {
    id: "41",
    name: "Personalized Learning AI",
    startDate: new Date("2025-08-01"),
    endDate: new Date("2025-08-31"),
    projectKey: "LEARN-041",
    status: "high",
    progress: 55,
    team: "engineering",
    priority: "high",
    category: "Advance Capabilities",
    riskLevel: "low"
  },
  {
    id: "42",
    name: "Digital Wallet Integration",
    startDate: new Date("2025-09-01"),
    endDate: new Date("2025-09-30"),
    projectKey: "WALLET-042",
    status: "medium",
    progress: 90,
    team: "engineering",
    priority: "high",
    category: "Evolving Cyber Threats",
    riskLevel: "medium"
  },
  {
    id: "43",
    name: "Smart Manufacturing",
    startDate: new Date("2025-10-01"),
    endDate: new Date("2025-10-31"),
    projectKey: "MANUF-043",
    status: "high",
    progress: 30,
    team: "product",
    priority: "high",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "44",
    name: "Neural Interface Development",
    startDate: new Date("2025-11-01"),
    endDate: new Date("2025-11-30"),
    projectKey: "NEURAL-044",
    status: "low",
    progress: 2,
    team: "engineering",
    priority: "high",
    category: "Data Analysis",
    riskLevel: "high"
  },
  {
    id: "45",
    name: "Climate Change Modeling",
    startDate: new Date("2025-12-01"),
    endDate: new Date("2025-12-31"),
    projectKey: "CLIMATE-045",
    status: "high",
    progress: 65,
    team: "other",
    priority: "high",
    category: "Advance Capabilities",
    riskLevel: "low"
  },
  {
    id: "46",
    name: "Holographic Display System",
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-01-31"),
    projectKey: "HOLO-046",
    status: "low",
    progress: 7,
    team: "engineering",
    priority: "high",
    category: "Advance Capabilities",
    riskLevel: "high"
  },
  {
    id: "47",
    name: "Space Communication Network",
    startDate: new Date("2024-02-01"),
    endDate: new Date("2024-02-29"),
    projectKey: "SPACE-047",
    status: "low",
    progress: 1,
    team: "engineering",
    priority: "high",
    category: "Advance Solutions",
    riskLevel: "high"
  },
  {
    id: "48",
    name: "Gene Therapy Database",
    startDate: new Date("2024-03-01"),
    endDate: new Date("2024-03-31"),
    projectKey: "GENE-048",
    status: "high",
    progress: 40,
    team: "engineering",
    priority: "high",
    category: "Data Analysis",
    riskLevel: "medium"
  },
  {
    id: "49",
    name: "Emotion Recognition AI",
    startDate: new Date("2024-04-01"),
    endDate: new Date("2024-04-30"),
    projectKey: "EMOTION-049",
    status: "medium",
    progress: 75,
    team: "engineering",
    priority: "high",
    category: "Advance Capabilities",
    riskLevel: "medium"
  },
  {
    id: "50",
    name: "Underwater Exploration Robot",
    startDate: new Date("2024-05-01"),
    endDate: new Date("2024-05-31"),
    projectKey: "WATER-050",
    status: "high",
    progress: 20,
    team: "engineering",
    priority: "high",
    category: "Advance Capabilities",
    riskLevel: "low"
  }
];