import type { ProjectDataType } from "./index";

export const Example_Issues_3: ProjectDataType[] = [
  {
    id: "101",
    name: "Digital Transformation Initiative",
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-12-31"),
    projectKey: "DIGITAL-101",
    status: "high",
    progress: 35,
    team: "engineering",
    priority: "high",
    category: "Advance Solutions",
    riskLevel: "high"
  },
  {
    id: "102",
    name: "Sustainability Roadmap",
    startDate: new Date("2024-02-01"),
    endDate: new Date("2024-12-31"),
    projectKey: "SUSTAIN-102",
    status: "medium",
    progress: 45,
    team: "other",
    priority: "high",
    category: "Advance Capabilities",
    riskLevel: "medium"
  },
  {
    id: "103",
    name: "Global Expansion Strategy",
    startDate: new Date("2024-03-01"),
    endDate: new Date("2024-12-31"),
    projectKey: "GLOBAL-103",
    status: "medium",
    progress: 30,
    team: "other",
    priority: "high",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "104",
    name: "Innovation Hub Development",
    startDate: new Date("2024-04-01"),
    endDate: new Date("2024-12-31"),
    projectKey: "INNOV-104",
    status: "low",
    progress: 15,
    team: "engineering",
    priority: "high",
    category: "Advance Capabilities",
    riskLevel: "low"
  },
  {
    id: "105",
    name: "Customer Experience Platform",
    startDate: new Date("2024-05-01"),
    endDate: new Date("2024-12-31"),
    projectKey: "CX-105",
    status: "medium",
    progress: 55,
    team: "engineering",
    priority: "high",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "106",
    name: "Cybersecurity Framework",
    startDate: new Date("2024-06-01"),
    endDate: new Date("2024-08-31"),
    projectKey: "CYBER-106",
    status: "medium",
    progress: 80,
    team: "engineering",
    priority: "high",
    category: "Evolving Cyber Threats",
    riskLevel: "medium"
  },
  {
    id: "107",
    name: "Store Layout Optimization",
    startDate: new Date("2024-07-01"),
    endDate: new Date("2024-07-31"),
    projectKey: "STORE-107",
    status: "low",
    progress: 20,
    team: "other",
    priority: "high",
    category: "To revolutionize retail experience through innovative technology",
    riskLevel: "low"
  },
  {
    id: "108",
    name: "Mobile Payment Integration",
    startDate: new Date("2024-08-01"),
    endDate: new Date("2024-10-31"),
    projectKey: "PAY-108",
    status: "medium",
    progress: 65,
    team: "engineering",
    priority: "high",
    category: "To revolutionize retail experience through innovative technology",
    riskLevel: "medium"
  },
  {
    id: "109",
    name: "Social Media Strategy",
    startDate: new Date("2024-09-01"),
    endDate: new Date("2024-09-30"),
    projectKey: "SOCIAL-109",
    status: "low",
    progress: 30,
    team: "marketing",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "110",
    name: "Diversity and Inclusion",
    startDate: new Date("2024-10-01"),
    endDate: new Date("2024-10-31"),
    projectKey: "DIV-110",
    status: "medium",
    progress: 45,
    team: "other",
    priority: "medium",
    category: "Advance Capabilities",
    riskLevel: "medium"
  },
  {
    id: "111",
    name: "Product Testing Lab",
    startDate: new Date("2024-11-01"),
    endDate: new Date("2024-11-30"),
    projectKey: "LAB-111",
    status: "low",
    progress: 15,
    team: "product",
    priority: "medium",
    category: "To revolutionize retail experience through innovative technology",
    riskLevel: "low"
  },
  {
    id: "112",
    name: "Customer Journey Analytics",
    startDate: new Date("2024-12-01"),
    endDate: new Date("2025-02-28"),
    projectKey: "JOURNEY-112",
    status: "medium",
    progress: 60,
    team: "engineering",
    priority: "medium",
    category: "To revolutionize retail experience through innovative technology",
    riskLevel: "medium"
  },
  {
    id: "113",
    name: "International Market Research",
    startDate: new Date("2025-01-01"),
    endDate: new Date("2025-01-31"),
    projectKey: "RESEARCH-113",
    status: "low",
    progress: 25,
    team: "other",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "114",
    name: "Warehouse Automation",
    startDate: new Date("2025-02-01"),
    endDate: new Date("2025-04-30"),
    projectKey: "WAREHOUSE-114",
    status: "medium",
    progress: 75,
    team: "other",
    priority: "medium",
    category: "To revolutionize retail experience through innovative technology",
    riskLevel: "medium"
  },
  {
    id: "115",
    name: "Influencer Marketing Program",
    startDate: new Date("2025-03-01"),
    endDate: new Date("2025-03-31"),
    projectKey: "INFLUENCER-115",
    status: "low",
    progress: 40,
    team: "marketing",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "116",
    name: "Employee Engagement Platform",
    startDate: new Date("2025-04-01"),
    endDate: new Date("2025-04-30"),
    projectKey: "ENGAGE-116",
    status: "medium",
    progress: 50,
    team: "other",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "117",
    name: "Store Performance Analytics",
    startDate: new Date("2025-05-01"),
    endDate: new Date("2025-05-31"),
    projectKey: "ANALYTICS-117",
    status: "low",
    progress: 20,
    team: "other",
    priority: "medium",
    category: "To revolutionize retail experience through innovative technology",
    riskLevel: "low"
  },
  {
    id: "118",
    name: "API Gateway Development",
    startDate: new Date("2025-06-01"),
    endDate: new Date("2025-08-31"),
    projectKey: "API-118",
    status: "medium",
    progress: 65,
    team: "engineering",
    priority: "medium",
    category: "To revolutionize retail experience through innovative technology",
    riskLevel: "medium"
  },
  {
    id: "119",
    name: "Product Lifecycle Management",
    startDate: new Date("2025-07-01"),
    endDate: new Date("2025-07-31"),
    projectKey: "PLM-119",
    status: "low",
    progress: 30,
    team: "product",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "120",
    name: "E-commerce Personalization",
    startDate: new Date("2025-08-01"),
    endDate: new Date("2025-10-31"),
    projectKey: "PERSONAL-120",
    status: "medium",
    progress: 55,
    team: "engineering",
    priority: "medium",
    category: "To revolutionize retail experience through innovative technology",
    riskLevel: "medium"
  },
  {
    id: "121",
    name: "Corporate Governance Review",
    startDate: new Date("2025-09-01"),
    endDate: new Date("2025-09-30"),
    projectKey: "GOVERN-121",
    status: "low",
    progress: 35,
    team: "other",
    priority: "medium",
    category: "Advance Capabilities",
    riskLevel: "low"
  },
  {
    id: "122",
    name: "Skills Development Program",
    startDate: new Date("2025-10-01"),
    endDate: new Date("2025-10-31"),
    projectKey: "SKILLS-122",
    status: "medium",
    progress: 45,
    team: "other",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "123",
    name: "Retail Analytics Platform",
    startDate: new Date("2025-11-01"),
    endDate: new Date("2025-11-30"),
    projectKey: "RETAIL-123",
    status: "low",
    progress: 25,
    team: "other",
    priority: "medium",
    category: "To revolutionize retail experience through innovative technology",
    riskLevel: "low"
  },
  {
    id: "124",
    name: "Brand Experience Design",
    startDate: new Date("2025-12-01"),
    endDate: new Date("2025-12-31"),
    projectKey: "BRAND-124",
    status: "medium",
    progress: 40,
    team: "marketing",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "125",
    name: "Supply Chain Optimization",
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-01-31"),
    projectKey: "SUPPLY-125",
    status: "low",
    progress: 30,
    team: "other",
    priority: "medium",
    category: "To revolutionize retail experience through innovative technology",
    riskLevel: "low"
  },
  {
    id: "126",
    name: "AI Customer Insights",
    startDate: new Date("2024-02-01"),
    endDate: new Date("2024-04-30"),
    projectKey: "AI-126",
    status: "medium",
    progress: 60,
    team: "engineering",
    priority: "medium",
    category: "To revolutionize retail experience through innovative technology",
    riskLevel: "medium"
  },
  {
    id: "127",
    name: "Store Digital Transformation",
    startDate: new Date("2024-03-01"),
    endDate: new Date("2024-03-31"),
    projectKey: "DIGITAL-127",
    status: "low",
    progress: 35,
    team: "other",
    priority: "medium",
    category: "To revolutionize retail experience through innovative technology",
    riskLevel: "low"
  },
  {
    id: "128",
    name: "E-commerce Platform Enhancement",
    startDate: new Date("2024-04-01"),
    endDate: new Date("2024-06-30"),
    projectKey: "ECOM-128",
    status: "medium",
    progress: 70,
    team: "engineering",
    priority: "medium",
    category: "To revolutionize retail experience through innovative technology",
    riskLevel: "medium"
  },
  {
    id: "129",
    name: "Brand Identity Evolution",
    startDate: new Date("2024-05-01"),
    endDate: new Date("2024-05-31"),
    projectKey: "BRAND-129",
    status: "low",
    progress: 45,
    team: "marketing",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "130",
    name: "Corporate Strategy Refresh",
    startDate: new Date("2024-06-01"),
    endDate: new Date("2024-06-30"),
    projectKey: "STRATEGY-130",
    status: "medium",
    progress: 50,
    team: "other",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "131",
    name: "Product Innovation Hub",
    startDate: new Date("2024-07-01"),
    endDate: new Date("2024-07-31"),
    projectKey: "INNOV-131",
    status: "low",
    progress: 25,
    team: "product",
    priority: "medium",
    category: "To revolutionize retail experience through innovative technology",
    riskLevel: "low"
  },
  {
    id: "132",
    name: "HR Digital Transformation",
    startDate: new Date("2024-08-01"),
    endDate: new Date("2024-08-31"),
    projectKey: "HR-132",
    status: "medium",
    progress: 55,
    team: "other",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "133",
    name: "Retail Experience Platform",
    startDate: new Date("2024-09-01"),
    endDate: new Date("2024-09-30"),
    projectKey: "RETAIL-133",
    status: "low",
    progress: 40,
    team: "other",
    priority: "medium",
    category: "To revolutionize retail experience through innovative technology",
    riskLevel: "low"
  },
  {
    id: "134",
    name: "Cloud Security Enhancement",
    startDate: new Date("2024-10-01"),
    endDate: new Date("2024-12-31"),
    projectKey: "CLOUD-134",
    status: "medium",
    progress: 65,
    team: "engineering",
    priority: "medium",
    category: "To revolutionize retail experience through innovative technology",
    riskLevel: "medium"
  },
  {
    id: "135",
    name: "E-commerce Analytics Platform",
    startDate: new Date("2024-11-01"),
    endDate: new Date("2024-11-30"),
    projectKey: "ANALYTICS-135",
    status: "low",
    progress: 35,
    team: "engineering",
    priority: "medium",
    category: "To revolutionize retail experience through innovative technology",
    riskLevel: "low"
  },
  {
    id: "136",
    name: "Brand Engagement Strategy",
    startDate: new Date("2024-12-01"),
    endDate: new Date("2024-12-31"),
    projectKey: "ENGAGE-136",
    status: "medium",
    progress: 45,
    team: "marketing",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "137",
    name: "Corporate Innovation Lab",
    startDate: new Date("2025-01-01"),
    endDate: new Date("2025-01-31"),
    projectKey: "LAB-137",
    status: "low",
    progress: 30,
    team: "other",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "138",
    name: "Product Quality System",
    startDate: new Date("2025-02-01"),
    endDate: new Date("2025-04-30"),
    projectKey: "QUALITY-138",
    status: "medium",
    progress: 60,
    team: "product",
    priority: "medium",
    category: "To revolutionize retail experience through innovative technology",
    riskLevel: "medium"
  },
  {
    id: "139",
    name: "Employee Development Platform",
    startDate: new Date("2025-03-01"),
    endDate: new Date("2025-03-31"),
    projectKey: "DEV-139",
    status: "low",
    progress: 40,
    team: "other",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "140",
    name: "Store Operations System",
    startDate: new Date("2025-04-01"),
    endDate: new Date("2025-04-30"),
    projectKey: "OPS-140",
    status: "medium",
    progress: 55,
    team: "other",
    priority: "medium",
    category: "To revolutionize retail experience through innovative technology",
    riskLevel: "medium"
  },
  {
    id: "141",
    name: "API Development Framework",
    startDate: new Date("2025-05-01"),
    endDate: new Date("2025-05-31"),
    projectKey: "API-141",
    status: "low",
    progress: 35,
    team: "engineering",
    priority: "medium",
    category: "To revolutionize retail experience through innovative technology",
    riskLevel: "low"
  },
  {
    id: "142",
    name: "E-commerce Platform Security",
    startDate: new Date("2025-06-01"),
    endDate: new Date("2025-08-31"),
    projectKey: "SEC-142",
    status: "medium",
    progress: 50,
    team: "engineering",
    priority: "medium",
    category: "To revolutionize retail experience through innovative technology",
    riskLevel: "medium"
  },
  {
    id: "143",
    name: "Brand Strategy Platform",
    startDate: new Date("2025-07-01"),
    endDate: new Date("2025-07-31"),
    projectKey: "BRAND-143",
    status: "low",
    progress: 45,
    team: "marketing",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "low"
  },
  {
    id: "144",
    name: "Corporate Risk Framework",
    startDate: new Date("2025-08-01"),
    endDate: new Date("2025-08-31"),
    projectKey: "RISK-144",
    status: "medium",
    progress: 40,
    team: "other",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "145",
    name: "Product Development System",
    startDate: new Date("2025-09-01"),
    endDate: new Date("2025-09-30"),
    projectKey: "DEV-145",
    status: "low",
    progress: 35,
    team: "product",
    priority: "medium",
    category: "To revolutionize retail experience through innovative technology",
    riskLevel: "low"
  },
  {
    id: "146",
    name: "HR Analytics System",
    startDate: new Date("2025-10-01"),
    endDate: new Date("2025-10-31"),
    projectKey: "HR-146",
    status: "medium",
    progress: 55,
    team: "other",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  },
  {
    id: "147",
    name: "Retail Intelligence Platform",
    startDate: new Date("2025-11-01"),
    endDate: new Date("2025-11-30"),
    projectKey: "INTEL-147",
    status: "low",
    progress: 30,
    team: "other",
    priority: "medium",
    category: "To revolutionize retail experience through innovative technology",
    riskLevel: "low"
  },
  {
    id: "148",
    name: "Cloud Infrastructure Upgrade",
    startDate: new Date("2025-12-01"),
    endDate: new Date("2026-02-28"),
    projectKey: "CLOUD-148",
    status: "medium",
    progress: 65,
    team: "engineering",
    priority: "medium",
    category: "To revolutionize retail experience through innovative technology",
    riskLevel: "medium"
  },
  {
    id: "149",
    name: "E-commerce Experience Platform",
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-01-31"),
    projectKey: "EXP-149",
    status: "low",
    progress: 40,
    team: "engineering",
    priority: "medium",
    category: "To revolutionize retail experience through innovative technology",
    riskLevel: "low"
  },
  {
    id: "150",
    name: "Brand Innovation Lab",
    startDate: new Date("2024-02-01"),
    endDate: new Date("2024-02-29"),
    projectKey: "BRAND-150",
    status: "medium",
    progress: 45,
    team: "marketing",
    priority: "medium",
    category: "Advance Solutions",
    riskLevel: "medium"
  }
]; 