import { IssueShapeKeys, type IssueShape } from "../../data-layer/types/timeline";

export const Example_Issues_3: IssueShape[] = [
  {
    [IssueShapeKeys.ID]: "101",
    [IssueShapeKeys.NAME]: "Digital Transformation Initiative",
    [IssueShapeKeys.STATUS]: "High Risks",
    [IssueShapeKeys.DESCRIPTION]: "Lead organization-wide digital transformation with focus on customer experience",
    [IssueShapeKeys.START_DATE]: new Date("2024-01-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-12-31"),
    [IssueShapeKeys.PROGRESS]: 35,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "102",
    [IssueShapeKeys.NAME]: "Sustainability Roadmap",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Develop and implement comprehensive sustainability strategy",
    [IssueShapeKeys.START_DATE]: new Date("2024-02-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-12-31"),
    [IssueShapeKeys.PROGRESS]: 45,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Corporate",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "103",
    [IssueShapeKeys.NAME]: "Global Expansion Strategy",
    [IssueShapeKeys.STATUS]: "Manageable Risk",
    [IssueShapeKeys.DESCRIPTION]: "Create and execute international market expansion plan",
    [IssueShapeKeys.START_DATE]: new Date("2024-03-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-12-31"),
    [IssueShapeKeys.PROGRESS]: 30,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Corporate",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "104",
    [IssueShapeKeys.NAME]: "Innovation Hub Development",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Establish dedicated innovation center for R&D and prototyping",
    [IssueShapeKeys.START_DATE]: new Date("2024-04-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-12-31"),
    [IssueShapeKeys.PROGRESS]: 15,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "105",
    [IssueShapeKeys.NAME]: "Customer Experience Platform",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Build unified customer experience platform across all channels",
    [IssueShapeKeys.START_DATE]: new Date("2024-05-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-12-31"),
    [IssueShapeKeys.PROGRESS]: 55,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "106",
    [IssueShapeKeys.NAME]: "Cybersecurity Framework",
    [IssueShapeKeys.STATUS]: "Manageable Risk",
    [IssueShapeKeys.DESCRIPTION]: "Implement comprehensive cybersecurity framework across all systems",
    [IssueShapeKeys.START_DATE]: new Date("2024-06-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-08-31"),
    [IssueShapeKeys.PROGRESS]: 80,
    [IssueShapeKeys.CATEGORY]: "Evolving Cyber Threats",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "107",
    [IssueShapeKeys.NAME]: "Store Layout Optimization",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Optimize store layouts based on customer behavior analytics",
    [IssueShapeKeys.START_DATE]: new Date("2024-07-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-07-31"),
    [IssueShapeKeys.PROGRESS]: 20,
    [IssueShapeKeys.CATEGORY]: "To revolutionize retail experience through innovative technology",
    [IssueShapeKeys.TEAM]: "Retail",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "108",
    [IssueShapeKeys.NAME]: "Mobile Payment Integration",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Implement new mobile payment solutions across all channels",
    [IssueShapeKeys.START_DATE]: new Date("2024-08-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-10-31"),
    [IssueShapeKeys.PROGRESS]: 65,
    [IssueShapeKeys.CATEGORY]: "To revolutionize retail experience through innovative technology",
    [IssueShapeKeys.TEAM]: "E-com",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "109",
    [IssueShapeKeys.NAME]: "Social Media Strategy",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Develop comprehensive social media marketing strategy",
    [IssueShapeKeys.START_DATE]: new Date("2024-09-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-09-30"),
    [IssueShapeKeys.PROGRESS]: 30,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Brand Marketing",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "110",
    [IssueShapeKeys.NAME]: "Diversity and Inclusion",
    [IssueShapeKeys.STATUS]: "Manageable Risk",
    [IssueShapeKeys.DESCRIPTION]: "Launch new diversity and inclusion initiatives across the organization",
    [IssueShapeKeys.START_DATE]: new Date("2024-10-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-10-31"),
    [IssueShapeKeys.PROGRESS]: 45,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Corporate",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "111",
    [IssueShapeKeys.NAME]: "Product Testing Lab",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Establish advanced product testing facility",
    [IssueShapeKeys.START_DATE]: new Date("2024-11-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-11-30"),
    [IssueShapeKeys.PROGRESS]: 15,
    [IssueShapeKeys.CATEGORY]: "To revolutionize retail experience through innovative technology",
    [IssueShapeKeys.TEAM]: "Product",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "112",
    [IssueShapeKeys.NAME]: "Customer Journey Analytics",
    [IssueShapeKeys.STATUS]: "Manageable Risk",
    [IssueShapeKeys.DESCRIPTION]: "Implement advanced analytics for customer journey mapping",
    [IssueShapeKeys.START_DATE]: new Date("2024-12-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-02-28"),
    [IssueShapeKeys.PROGRESS]: 60,
    [IssueShapeKeys.CATEGORY]: "To revolutionize retail experience through innovative technology",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "113",
    [IssueShapeKeys.NAME]: "International Market Research",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Conduct comprehensive research for new market entry",
    [IssueShapeKeys.START_DATE]: new Date("2025-01-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-01-31"),
    [IssueShapeKeys.PROGRESS]: 25,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Corporate",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "114",
    [IssueShapeKeys.NAME]: "Warehouse Automation",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Implement automated warehouse management system",
    [IssueShapeKeys.START_DATE]: new Date("2025-02-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-04-30"),
    [IssueShapeKeys.PROGRESS]: 75,
    [IssueShapeKeys.CATEGORY]: "To revolutionize retail experience through innovative technology",
    [IssueShapeKeys.TEAM]: "Fulfillment",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "115",
    [IssueShapeKeys.NAME]: "Influencer Marketing Program",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Launch strategic influencer marketing campaign",
    [IssueShapeKeys.START_DATE]: new Date("2025-03-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-03-31"),
    [IssueShapeKeys.PROGRESS]: 40,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Brand Marketing",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "116",
    [IssueShapeKeys.NAME]: "Employee Engagement Platform",
    [IssueShapeKeys.STATUS]: "Manageable Risk",
    [IssueShapeKeys.DESCRIPTION]: "Develop new employee engagement and feedback system",
    [IssueShapeKeys.START_DATE]: new Date("2025-04-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-04-30"),
    [IssueShapeKeys.PROGRESS]: 50,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Function",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "117",
    [IssueShapeKeys.NAME]: "Store Performance Analytics",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Implement advanced analytics for store performance tracking",
    [IssueShapeKeys.START_DATE]: new Date("2025-05-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-05-31"),
    [IssueShapeKeys.PROGRESS]: 20,
    [IssueShapeKeys.CATEGORY]: "To revolutionize retail experience through innovative technology",
    [IssueShapeKeys.TEAM]: "Retail",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "118",
    [IssueShapeKeys.NAME]: "API Gateway Development",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Build centralized API gateway for microservices",
    [IssueShapeKeys.START_DATE]: new Date("2025-06-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-08-31"),
    [IssueShapeKeys.PROGRESS]: 65,
    [IssueShapeKeys.CATEGORY]: "To revolutionize retail experience through innovative technology",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "119",
    [IssueShapeKeys.NAME]: "Product Lifecycle Management",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Implement comprehensive product lifecycle management system",
    [IssueShapeKeys.START_DATE]: new Date("2025-07-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-07-31"),
    [IssueShapeKeys.PROGRESS]: 30,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Product",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "120",
    [IssueShapeKeys.NAME]: "E-commerce Personalization",
    [IssueShapeKeys.STATUS]: "Manageable Risk",
    [IssueShapeKeys.DESCRIPTION]: "Implement AI-driven personalization for online shopping",
    [IssueShapeKeys.START_DATE]: new Date("2025-08-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-10-31"),
    [IssueShapeKeys.PROGRESS]: 55,
    [IssueShapeKeys.CATEGORY]: "To revolutionize retail experience through innovative technology",
    [IssueShapeKeys.TEAM]: "E-com",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "121",
    [IssueShapeKeys.NAME]: "Corporate Governance Review",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Conduct comprehensive review of corporate governance framework",
    [IssueShapeKeys.START_DATE]: new Date("2025-09-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-09-30"),
    [IssueShapeKeys.PROGRESS]: 35,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Corporate",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "122",
    [IssueShapeKeys.NAME]: "Skills Development Program",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Launch new skills development initiative for employees",
    [IssueShapeKeys.START_DATE]: new Date("2025-10-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-10-31"),
    [IssueShapeKeys.PROGRESS]: 45,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Function",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "123",
    [IssueShapeKeys.NAME]: "Retail Analytics Platform",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Develop advanced analytics platform for retail operations",
    [IssueShapeKeys.START_DATE]: new Date("2025-11-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-11-30"),
    [IssueShapeKeys.PROGRESS]: 25,
    [IssueShapeKeys.CATEGORY]: "To revolutionize retail experience through innovative technology",
    [IssueShapeKeys.TEAM]: "Retail",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "124",
    [IssueShapeKeys.NAME]: "Brand Experience Design",
    [IssueShapeKeys.STATUS]: "Manageable Risk",
    [IssueShapeKeys.DESCRIPTION]: "Create immersive brand experience across all touchpoints",
    [IssueShapeKeys.START_DATE]: new Date("2025-12-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-12-31"),
    [IssueShapeKeys.PROGRESS]: 40,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Brand Marketing",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "125",
    [IssueShapeKeys.NAME]: "Supply Chain Optimization",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Implement advanced supply chain optimization algorithms",
    [IssueShapeKeys.START_DATE]: new Date("2024-01-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-01-31"),
    [IssueShapeKeys.PROGRESS]: 30,
    [IssueShapeKeys.CATEGORY]: "To revolutionize retail experience through innovative technology",
    [IssueShapeKeys.TEAM]: "Fulfillment",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "126",
    [IssueShapeKeys.NAME]: "AI Customer Insights",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Develop AI-powered customer behavior analysis system",
    [IssueShapeKeys.START_DATE]: new Date("2024-02-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-04-30"),
    [IssueShapeKeys.PROGRESS]: 60,
    [IssueShapeKeys.CATEGORY]: "To revolutionize retail experience through innovative technology",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "127",
    [IssueShapeKeys.NAME]: "Store Digital Transformation",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Implement comprehensive digital transformation in retail stores",
    [IssueShapeKeys.START_DATE]: new Date("2024-03-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-03-31"),
    [IssueShapeKeys.PROGRESS]: 35,
    [IssueShapeKeys.CATEGORY]: "To revolutionize retail experience through innovative technology",
    [IssueShapeKeys.TEAM]: "Retail",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "128",
    [IssueShapeKeys.NAME]: "E-commerce Platform Enhancement",
    [IssueShapeKeys.STATUS]: "Manageable Risk",
    [IssueShapeKeys.DESCRIPTION]: "Enhance e-commerce platform with advanced features",
    [IssueShapeKeys.START_DATE]: new Date("2024-04-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-06-30"),
    [IssueShapeKeys.PROGRESS]: 70,
    [IssueShapeKeys.CATEGORY]: "To revolutionize retail experience through innovative technology",
    [IssueShapeKeys.TEAM]: "E-com",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "129",
    [IssueShapeKeys.NAME]: "Brand Identity Evolution",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Evolve brand identity for modern market demands",
    [IssueShapeKeys.START_DATE]: new Date("2024-05-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-05-31"),
    [IssueShapeKeys.PROGRESS]: 45,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Brand Marketing",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "130",
    [IssueShapeKeys.NAME]: "Corporate Strategy Refresh",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Update corporate strategy for new market conditions",
    [IssueShapeKeys.START_DATE]: new Date("2024-06-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-06-30"),
    [IssueShapeKeys.PROGRESS]: 50,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Corporate",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "131",
    [IssueShapeKeys.NAME]: "Product Innovation Hub",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Establish innovation hub for product development",
    [IssueShapeKeys.START_DATE]: new Date("2024-07-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-07-31"),
    [IssueShapeKeys.PROGRESS]: 25,
    [IssueShapeKeys.CATEGORY]: "To revolutionize retail experience through innovative technology",
    [IssueShapeKeys.TEAM]: "Product",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "132",
    [IssueShapeKeys.NAME]: "HR Digital Transformation",
    [IssueShapeKeys.STATUS]: "Manageable Risk",
    [IssueShapeKeys.DESCRIPTION]: "Implement digital HR management solutions",
    [IssueShapeKeys.START_DATE]: new Date("2024-08-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-08-31"),
    [IssueShapeKeys.PROGRESS]: 55,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Function",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "133",
    [IssueShapeKeys.NAME]: "Retail Experience Platform",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Develop unified retail experience platform",
    [IssueShapeKeys.START_DATE]: new Date("2024-09-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-09-30"),
    [IssueShapeKeys.PROGRESS]: 40,
    [IssueShapeKeys.CATEGORY]: "To revolutionize retail experience through innovative technology",
    [IssueShapeKeys.TEAM]: "Retail",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "134",
    [IssueShapeKeys.NAME]: "Cloud Security Enhancement",
    [IssueShapeKeys.STATUS]: "Manageable Risk",
    [IssueShapeKeys.DESCRIPTION]: "Enhance cloud security infrastructure",
    [IssueShapeKeys.START_DATE]: new Date("2024-10-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-12-31"),
    [IssueShapeKeys.PROGRESS]: 65,
    [IssueShapeKeys.CATEGORY]: "To revolutionize retail experience through innovative technology",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "135",
    [IssueShapeKeys.NAME]: "E-commerce Analytics Platform",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Develop comprehensive e-commerce analytics platform",
    [IssueShapeKeys.START_DATE]: new Date("2024-11-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-11-30"),
    [IssueShapeKeys.PROGRESS]: 35,
    [IssueShapeKeys.CATEGORY]: "To revolutionize retail experience through innovative technology",
    [IssueShapeKeys.TEAM]: "E-com",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "136",
    [IssueShapeKeys.NAME]: "Brand Engagement Strategy",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Develop new brand engagement strategy",
    [IssueShapeKeys.START_DATE]: new Date("2024-12-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-12-31"),
    [IssueShapeKeys.PROGRESS]: 45,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Brand Marketing",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "137",
    [IssueShapeKeys.NAME]: "Corporate Innovation Lab",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Establish corporate innovation laboratory",
    [IssueShapeKeys.START_DATE]: new Date("2025-01-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-01-31"),
    [IssueShapeKeys.PROGRESS]: 30,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Corporate",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "138",
    [IssueShapeKeys.NAME]: "Product Quality System",
    [IssueShapeKeys.STATUS]: "Manageable Risk",
    [IssueShapeKeys.DESCRIPTION]: "Implement comprehensive product quality management system",
    [IssueShapeKeys.START_DATE]: new Date("2025-02-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-04-30"),
    [IssueShapeKeys.PROGRESS]: 60,
    [IssueShapeKeys.CATEGORY]: "To revolutionize retail experience through innovative technology",
    [IssueShapeKeys.TEAM]: "Product",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "139",
    [IssueShapeKeys.NAME]: "Employee Development Platform",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Develop employee development and training platform",
    [IssueShapeKeys.START_DATE]: new Date("2025-03-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-03-31"),
    [IssueShapeKeys.PROGRESS]: 40,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Function",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "140",
    [IssueShapeKeys.NAME]: "Store Operations System",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Implement advanced store operations management system",
    [IssueShapeKeys.START_DATE]: new Date("2025-04-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-04-30"),
    [IssueShapeKeys.PROGRESS]: 55,
    [IssueShapeKeys.CATEGORY]: "To revolutionize retail experience through innovative technology",
    [IssueShapeKeys.TEAM]: "Retail",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "141",
    [IssueShapeKeys.NAME]: "API Development Framework",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Create standardized API development framework",
    [IssueShapeKeys.START_DATE]: new Date("2025-05-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-05-31"),
    [IssueShapeKeys.PROGRESS]: 35,
    [IssueShapeKeys.CATEGORY]: "To revolutionize retail experience through innovative technology",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "142",
    [IssueShapeKeys.NAME]: "E-commerce Platform Security",
    [IssueShapeKeys.STATUS]: "Manageable Risk",
    [IssueShapeKeys.DESCRIPTION]: "Enhance e-commerce platform security measures",
    [IssueShapeKeys.START_DATE]: new Date("2025-06-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-08-31"),
    [IssueShapeKeys.PROGRESS]: 50,
    [IssueShapeKeys.CATEGORY]: "To revolutionize retail experience through innovative technology",
    [IssueShapeKeys.TEAM]: "E-com",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "143",
    [IssueShapeKeys.NAME]: "Brand Strategy Platform",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Develop comprehensive brand strategy platform",
    [IssueShapeKeys.START_DATE]: new Date("2025-07-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-07-31"),
    [IssueShapeKeys.PROGRESS]: 45,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Brand Marketing",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "144",
    [IssueShapeKeys.NAME]: "Corporate Risk Framework",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Implement enterprise risk management framework",
    [IssueShapeKeys.START_DATE]: new Date("2025-08-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-08-31"),
    [IssueShapeKeys.PROGRESS]: 40,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Corporate",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "145",
    [IssueShapeKeys.NAME]: "Product Development System",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Implement new product development management system",
    [IssueShapeKeys.START_DATE]: new Date("2025-09-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-09-30"),
    [IssueShapeKeys.PROGRESS]: 35,
    [IssueShapeKeys.CATEGORY]: "To revolutionize retail experience through innovative technology",
    [IssueShapeKeys.TEAM]: "Product",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "146",
    [IssueShapeKeys.NAME]: "HR Analytics System",
    [IssueShapeKeys.STATUS]: "Manageable Risk",
    [IssueShapeKeys.DESCRIPTION]: "Develop comprehensive HR analytics platform",
    [IssueShapeKeys.START_DATE]: new Date("2025-10-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-10-31"),
    [IssueShapeKeys.PROGRESS]: 55,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Function",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "147",
    [IssueShapeKeys.NAME]: "Retail Intelligence Platform",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Develop retail intelligence and analytics platform",
    [IssueShapeKeys.START_DATE]: new Date("2025-11-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-11-30"),
    [IssueShapeKeys.PROGRESS]: 30,
    [IssueShapeKeys.CATEGORY]: "To revolutionize retail experience through innovative technology",
    [IssueShapeKeys.TEAM]: "Retail",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "148",
    [IssueShapeKeys.NAME]: "Cloud Infrastructure Upgrade",
    [IssueShapeKeys.STATUS]: "Manageable Risk",
    [IssueShapeKeys.DESCRIPTION]: "Upgrade cloud infrastructure for improved performance",
    [IssueShapeKeys.START_DATE]: new Date("2025-12-01"),
    [IssueShapeKeys.END_DATE]: new Date("2026-02-28"),
    [IssueShapeKeys.PROGRESS]: 65,
    [IssueShapeKeys.CATEGORY]: "To revolutionize retail experience through innovative technology",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "149",
    [IssueShapeKeys.NAME]: "E-commerce Experience Platform",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Develop unified e-commerce experience platform",
    [IssueShapeKeys.START_DATE]: new Date("2024-01-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-01-31"),
    [IssueShapeKeys.PROGRESS]: 40,
    [IssueShapeKeys.CATEGORY]: "To revolutionize retail experience through innovative technology",
    [IssueShapeKeys.TEAM]: "E-com",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "150",
    [IssueShapeKeys.NAME]: "Brand Innovation Lab",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Establish brand innovation laboratory",
    [IssueShapeKeys.START_DATE]: new Date("2024-02-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-02-29"),
    [IssueShapeKeys.PROGRESS]: 45,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Brand Marketing",
    [IssueShapeKeys.PRIORITY]: "Medium"
  }
]; 