import { IssueShapeKeys, type IssueShape } from "../../data-layer/types/timeline";

// Example goes here

export const Example_Issues_1: IssueShape[] = [
  {
    [IssueShapeKeys.ID]: "1",
    [IssueShapeKeys.NAME]: "Interactive Calculus Workshop",
    [IssueShapeKeys.STATUS]: "High Risks",
    [IssueShapeKeys.DESCRIPTION]: "Develop and implement an interactive workshop series for advanced calculus concepts using real-world applications",
    [IssueShapeKeys.START_DATE]: new Date("2024-01-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-01-31"),
    [IssueShapeKeys.PROGRESS]: 50,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Function",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "2",
    [IssueShapeKeys.NAME]: "Mobile App Development",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Create a cross-platform mobile application for task management with real-time synchronization",
    [IssueShapeKeys.START_DATE]: new Date("2024-02-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-03-31"),
    [IssueShapeKeys.PROGRESS]: 100,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "Low"
  },
  {
    [IssueShapeKeys.ID]: "3",
    [IssueShapeKeys.NAME]: "Machine Learning Model Training",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Train and deploy a neural network for image recognition with 95% accuracy",
    [IssueShapeKeys.START_DATE]: new Date("2024-03-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-03-31"),
    [IssueShapeKeys.PROGRESS]: 100,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "Low"
  },
  {
    [IssueShapeKeys.ID]: "4",
    [IssueShapeKeys.NAME]: "Website Redesign Project",
    [IssueShapeKeys.STATUS]: "Manageable Risk",
    [IssueShapeKeys.DESCRIPTION]: "Complete overhaul of company website with modern UI/UX principles and responsive design",
    [IssueShapeKeys.START_DATE]: new Date("2024-04-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-04-30"),
    [IssueShapeKeys.PROGRESS]: 75,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "E-com",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "5",
    [IssueShapeKeys.NAME]: "Data Migration Initiative",
    [IssueShapeKeys.STATUS]: "High Risks",
    [IssueShapeKeys.DESCRIPTION]: "Migrate legacy database systems to cloud-based infrastructure with zero downtime",
    [IssueShapeKeys.START_DATE]: new Date("2024-05-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-05-31"),
    [IssueShapeKeys.PROGRESS]: 25,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "6",
    [IssueShapeKeys.NAME]: "Customer Support Automation",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Implement AI-powered chatbot to handle 80% of customer inquiries automatically",
    [IssueShapeKeys.START_DATE]: new Date("2024-06-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-06-30"),
    [IssueShapeKeys.PROGRESS]: 60,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Retail",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "7",
    [IssueShapeKeys.NAME]: "Blockchain Integration",
    [IssueShapeKeys.STATUS]: "High Risks",
    [IssueShapeKeys.DESCRIPTION]: "Integrate blockchain technology for secure transaction processing and data integrity",
    [IssueShapeKeys.START_DATE]: new Date("2024-07-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-08-31"),
    [IssueShapeKeys.PROGRESS]: 5,
    [IssueShapeKeys.CATEGORY]: "Evolving Cyber Threats",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "8",
    [IssueShapeKeys.NAME]: "IoT Sensor Network",
    [IssueShapeKeys.STATUS]: "Manageable Risk",
    [IssueShapeKeys.DESCRIPTION]: "Deploy Internet of Things sensors for real-time environmental monitoring",
    [IssueShapeKeys.START_DATE]: new Date("2024-08-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-08-31"),
    [IssueShapeKeys.PROGRESS]: 40,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "9",
    [IssueShapeKeys.NAME]: "Cybersecurity Audit",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Comprehensive security assessment and vulnerability testing of all systems",
    [IssueShapeKeys.START_DATE]: new Date("2024-09-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-09-30"),
    [IssueShapeKeys.PROGRESS]: 100,
    [IssueShapeKeys.CATEGORY]: "Evolving Cyber Threats",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "10",
    [IssueShapeKeys.NAME]: "Virtual Reality Training Platform",
    [IssueShapeKeys.STATUS]: "Manageable Risk",
    [IssueShapeKeys.DESCRIPTION]: "Develop immersive VR training modules for employee skill development",
    [IssueShapeKeys.START_DATE]: new Date("2024-10-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-10-31"),
    [IssueShapeKeys.PROGRESS]: 35,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Function",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "11",
    [IssueShapeKeys.NAME]: "API Gateway Implementation",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Build and deploy centralized API gateway for microservices architecture",
    [IssueShapeKeys.START_DATE]: new Date("2024-11-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-11-30"),
    [IssueShapeKeys.PROGRESS]: 85,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "12",
    [IssueShapeKeys.NAME]: "Cloud Migration Strategy",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Develop comprehensive strategy for migrating on-premise infrastructure to AWS",
    [IssueShapeKeys.START_DATE]: new Date("2024-12-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-12-31"),
    [IssueShapeKeys.PROGRESS]: 10,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "13",
    [IssueShapeKeys.NAME]: "User Authentication System",
    [IssueShapeKeys.STATUS]: "High Risks",
    [IssueShapeKeys.DESCRIPTION]: "Implement multi-factor authentication with biometric support",
    [IssueShapeKeys.START_DATE]: new Date("2025-01-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-01-31"),
    [IssueShapeKeys.PROGRESS]: 65,
    [IssueShapeKeys.CATEGORY]: "Evolving Cyber Threats",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "14",
    [IssueShapeKeys.NAME]: "Analytics Dashboard",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Create real-time analytics dashboard with interactive visualizations",
    [IssueShapeKeys.START_DATE]: new Date("2025-02-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-02-28"),
    [IssueShapeKeys.PROGRESS]: 100,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "15",
    [IssueShapeKeys.NAME]: "Automated Testing Framework",
    [IssueShapeKeys.STATUS]: "Manageable Risk",
    [IssueShapeKeys.DESCRIPTION]: "Develop comprehensive automated testing suite for continuous integration",
    [IssueShapeKeys.START_DATE]: new Date("2025-03-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-04-30"),
    [IssueShapeKeys.PROGRESS]: 70,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "16",
    [IssueShapeKeys.NAME]: "Digital Twin Development",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Create digital twin models for predictive maintenance and optimization",
    [IssueShapeKeys.START_DATE]: new Date("2025-05-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-05-31"),
    [IssueShapeKeys.PROGRESS]: 5,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "17",
    [IssueShapeKeys.NAME]: "Supply Chain Optimization",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Implement AI-driven supply chain management for cost reduction and efficiency",
    [IssueShapeKeys.START_DATE]: new Date("2025-06-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-06-30"),
    [IssueShapeKeys.PROGRESS]: 45,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Fulfillment",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "18",
    [IssueShapeKeys.NAME]: "Microservices Architecture",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Decompose monolithic application into scalable microservices",
    [IssueShapeKeys.START_DATE]: new Date("2025-07-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-07-31"),
    [IssueShapeKeys.PROGRESS]: 100,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "19",
    [IssueShapeKeys.NAME]: "Edge Computing Infrastructure",
    [IssueShapeKeys.STATUS]: "Manageable Risk",
    [IssueShapeKeys.DESCRIPTION]: "Deploy edge computing nodes for reduced latency and improved performance",
    [IssueShapeKeys.START_DATE]: new Date("2025-08-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-08-31"),
    [IssueShapeKeys.PROGRESS]: 30,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "20",
    [IssueShapeKeys.NAME]: "Quantum Computing Research",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Explore quantum computing applications for complex optimization problems",
    [IssueShapeKeys.START_DATE]: new Date("2025-09-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-09-30"),
    [IssueShapeKeys.PROGRESS]: 8,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "21",
    [IssueShapeKeys.NAME]: "Green Energy Management",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Implement smart energy management system for renewable energy optimization",
    [IssueShapeKeys.START_DATE]: new Date("2025-10-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-11-30"),
    [IssueShapeKeys.PROGRESS]: 55,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Corporate",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "22",
    [IssueShapeKeys.NAME]: "Healthcare Data Platform",
    [IssueShapeKeys.STATUS]: "Manageable Risk",
    [IssueShapeKeys.DESCRIPTION]: "Develop HIPAA-compliant healthcare data analytics platform",
    [IssueShapeKeys.START_DATE]: new Date("2025-12-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-12-31"),
    [IssueShapeKeys.PROGRESS]: 90,
    [IssueShapeKeys.CATEGORY]: "Data Analysis",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "23",
    [IssueShapeKeys.NAME]: "Augmented Reality Interface",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Create AR interface for industrial maintenance and training applications",
    [IssueShapeKeys.START_DATE]: new Date("2024-01-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-01-31"),
    [IssueShapeKeys.PROGRESS]: 25,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "24",
    [IssueShapeKeys.NAME]: "Natural Language Processing",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Deploy NLP system for automated document processing and analysis",
    [IssueShapeKeys.START_DATE]: new Date("2024-02-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-02-29"),
    [IssueShapeKeys.PROGRESS]: 100,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "25",
    [IssueShapeKeys.NAME]: "Robotic Process Automation",
    [IssueShapeKeys.STATUS]: "Manageable Risk",
    [IssueShapeKeys.DESCRIPTION]: "Automate repetitive business processes using RPA technologies",
    [IssueShapeKeys.START_DATE]: new Date("2024-03-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-03-31"),
    [IssueShapeKeys.PROGRESS]: 50,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Function",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "26",
    [IssueShapeKeys.NAME]: "5G Network Integration",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Integrate 5G connectivity for ultra-low latency applications",
    [IssueShapeKeys.START_DATE]: new Date("2024-04-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-04-30"),
    [IssueShapeKeys.PROGRESS]: 12,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "27",
    [IssueShapeKeys.NAME]: "Digital Identity Platform",
    [IssueShapeKeys.STATUS]: "High Risks",
    [IssueShapeKeys.DESCRIPTION]: "Build decentralized identity management system using blockchain",
    [IssueShapeKeys.START_DATE]: new Date("2024-05-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-05-31"),
    [IssueShapeKeys.PROGRESS]: 40,
    [IssueShapeKeys.CATEGORY]: "Evolving Cyber Threats",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "28",
    [IssueShapeKeys.NAME]: "Computer Vision System",
    [IssueShapeKeys.STATUS]: "Manageable Risk",
    [IssueShapeKeys.DESCRIPTION]: "Implement computer vision for quality control in manufacturing",
    [IssueShapeKeys.START_DATE]: new Date("2024-06-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-06-30"),
    [IssueShapeKeys.PROGRESS]: 80,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "29",
    [IssueShapeKeys.NAME]: "Smart City Infrastructure",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Design IoT-enabled smart city infrastructure for traffic and utilities",
    [IssueShapeKeys.START_DATE]: new Date("2024-07-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-07-31"),
    [IssueShapeKeys.PROGRESS]: 100,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Corporate",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "30",
    [IssueShapeKeys.NAME]: "Predictive Analytics Engine",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Develop machine learning models for business forecasting and trend analysis",
    [IssueShapeKeys.START_DATE]: new Date("2024-08-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-08-31"),
    [IssueShapeKeys.PROGRESS]: 60,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "31",
    [IssueShapeKeys.NAME]: "Voice Recognition System",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Implement multi-language voice recognition for accessibility features",
    [IssueShapeKeys.START_DATE]: new Date("2024-09-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-09-30"),
    [IssueShapeKeys.PROGRESS]: 100,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "32",
    [IssueShapeKeys.NAME]: "Distributed Database System",
    [IssueShapeKeys.STATUS]: "Manageable Risk",
    [IssueShapeKeys.DESCRIPTION]: "Deploy distributed database with automatic sharding and replication",
    [IssueShapeKeys.START_DATE]: new Date("2024-10-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-10-31"),
    [IssueShapeKeys.PROGRESS]: 35,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "33",
    [IssueShapeKeys.NAME]: "Drone Delivery Network",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Establish autonomous drone delivery system for last-mile logistics",
    [IssueShapeKeys.START_DATE]: new Date("2024-11-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-11-30"),
    [IssueShapeKeys.PROGRESS]: 8,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Fulfillment",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "34",
    [IssueShapeKeys.NAME]: "Facial Recognition Security",
    [IssueShapeKeys.STATUS]: "Manageable Risk",
    [IssueShapeKeys.DESCRIPTION]: "Deploy facial recognition system for secure facility access control",
    [IssueShapeKeys.START_DATE]: new Date("2024-12-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-12-31"),
    [IssueShapeKeys.PROGRESS]: 85,
    [IssueShapeKeys.CATEGORY]: "Evolving Cyber Threats",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "35",
    [IssueShapeKeys.NAME]: "Environmental Monitoring",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Create comprehensive environmental monitoring system using satellite data",
    [IssueShapeKeys.START_DATE]: new Date("2025-01-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-01-31"),
    [IssueShapeKeys.PROGRESS]: 45,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Corporate",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "36",
    [IssueShapeKeys.NAME]: "Automated Code Generation",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Develop AI system for automated code generation from natural language",
    [IssueShapeKeys.START_DATE]: new Date("2025-02-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-02-28"),
    [IssueShapeKeys.PROGRESS]: 100,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "37",
    [IssueShapeKeys.NAME]: "Smart Grid Integration",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Integrate renewable energy sources into intelligent power grid system",
    [IssueShapeKeys.START_DATE]: new Date("2025-03-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-03-31"),
    [IssueShapeKeys.PROGRESS]: 25,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Corporate",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "38",
    [IssueShapeKeys.NAME]: "Biometric Payment System",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Implement biometric-based payment system for enhanced security",
    [IssueShapeKeys.START_DATE]: new Date("2025-04-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-04-30"),
    [IssueShapeKeys.PROGRESS]: 100,
    [IssueShapeKeys.CATEGORY]: "Evolving Cyber Threats",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "39",
    [IssueShapeKeys.NAME]: "Real-time Translation",
    [IssueShapeKeys.STATUS]: "Manageable Risk",
    [IssueShapeKeys.DESCRIPTION]: "Deploy real-time language translation system for global communication",
    [IssueShapeKeys.START_DATE]: new Date("2025-05-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-06-30"),
    [IssueShapeKeys.PROGRESS]: 70,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "40",
    [IssueShapeKeys.NAME]: "Autonomous Vehicle Platform",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Develop autonomous vehicle control system with advanced AI algorithms",
    [IssueShapeKeys.START_DATE]: new Date("2025-07-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-07-31"),
    [IssueShapeKeys.PROGRESS]: 100,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "41",
    [IssueShapeKeys.NAME]: "Personalized Learning AI",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Create AI-powered personalized learning platform for adaptive education",
    [IssueShapeKeys.START_DATE]: new Date("2025-08-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-08-31"),
    [IssueShapeKeys.PROGRESS]: 55,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Function",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "42",
    [IssueShapeKeys.NAME]: "Digital Wallet Integration",
    [IssueShapeKeys.STATUS]: "Manageable Risk",
    [IssueShapeKeys.DESCRIPTION]: "Integrate multiple digital payment methods into unified wallet system",
    [IssueShapeKeys.START_DATE]: new Date("2025-09-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-09-30"),
    [IssueShapeKeys.PROGRESS]: 90,
    [IssueShapeKeys.CATEGORY]: "Evolving Cyber Threats",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "43",
    [IssueShapeKeys.NAME]: "Smart Manufacturing",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Implement Industry 4.0 technologies for intelligent manufacturing processes",
    [IssueShapeKeys.START_DATE]: new Date("2025-10-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-10-31"),
    [IssueShapeKeys.PROGRESS]: 30,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Product",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "44",
    [IssueShapeKeys.NAME]: "Neural Interface Development",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Research brain-computer interfaces for assistive technologies",
    [IssueShapeKeys.START_DATE]: new Date("2025-11-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-11-30"),
    [IssueShapeKeys.PROGRESS]: 2,
    [IssueShapeKeys.CATEGORY]: "Data Analysis",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "45",
    [IssueShapeKeys.NAME]: "Climate Change Modeling",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Develop advanced climate models using supercomputing and AI",
    [IssueShapeKeys.START_DATE]: new Date("2025-12-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-12-31"),
    [IssueShapeKeys.PROGRESS]: 65,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Corporate",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "46",
    [IssueShapeKeys.NAME]: "Holographic Display System",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Create holographic display technology for immersive data visualization",
    [IssueShapeKeys.START_DATE]: new Date("2024-01-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-01-31"),
    [IssueShapeKeys.PROGRESS]: 7,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "47",
    [IssueShapeKeys.NAME]: "Space Communication Network",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Develop satellite-based communication network for global connectivity",
    [IssueShapeKeys.START_DATE]: new Date("2024-02-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-02-29"),
    [IssueShapeKeys.PROGRESS]: 1,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "48",
    [IssueShapeKeys.NAME]: "Gene Therapy Database",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Build secure database for gene therapy research and clinical trials",
    [IssueShapeKeys.START_DATE]: new Date("2024-03-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-03-31"),
    [IssueShapeKeys.PROGRESS]: 40,
    [IssueShapeKeys.CATEGORY]: "Data Analysis",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "49",
    [IssueShapeKeys.NAME]: "Emotion Recognition AI",
    [IssueShapeKeys.STATUS]: "Manageable Risk",
    [IssueShapeKeys.DESCRIPTION]: "Develop AI system for real-time emotion recognition and response",
    [IssueShapeKeys.START_DATE]: new Date("2024-04-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-04-30"),
    [IssueShapeKeys.PROGRESS]: 75,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "50",
    [IssueShapeKeys.NAME]: "Underwater Exploration Robot",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Design autonomous underwater vehicle for deep-sea exploration and research",
    [IssueShapeKeys.START_DATE]: new Date("2024-05-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-05-31"),
    [IssueShapeKeys.PROGRESS]: 20,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
];
