import { IssueShapeKeys, type IssueShape } from "../../data-layer/types/timeline";

export const Example_Issues_2: IssueShape[] = [
  {
    [IssueShapeKeys.ID]: "51",
    [IssueShapeKeys.NAME]: "AI-Powered Customer Service",
    [IssueShapeKeys.STATUS]: "High Risks",
    [IssueShapeKeys.DESCRIPTION]: "Implement AI chatbot for 24/7 customer support with natural language processing",
    [IssueShapeKeys.START_DATE]: new Date("2024-01-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-01-31"),
    [IssueShapeKeys.PROGRESS]: 65,
    [IssueShapeKeys.CATEGORY]: "Revolutionize Customer Experience",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "52",
    [IssueShapeKeys.NAME]: "Sustainable Packaging Initiative",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Develop and implement eco-friendly packaging solutions across all product lines",
    [IssueShapeKeys.START_DATE]: new Date("2024-02-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-02-29"),
    [IssueShapeKeys.PROGRESS]: 20,
    [IssueShapeKeys.CATEGORY]: "The Consistancy of Axiom of Choice and General Continuum Hypothesis in the Context of Set Theory",
    [IssueShapeKeys.TEAM]: "Product",
    [IssueShapeKeys.PRIORITY]: "High"
  },
  {
    [IssueShapeKeys.ID]: "53",
    [IssueShapeKeys.NAME]: "Mobile App Redesign",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Complete overhaul of mobile application with modern UI/UX principles",
    [IssueShapeKeys.START_DATE]: new Date("2024-03-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-03-31"),
    [IssueShapeKeys.PROGRESS]: 45,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "54",
    [IssueShapeKeys.NAME]: "Global Supply Chain Optimization",
    [IssueShapeKeys.STATUS]: "Manageable Risk",
    [IssueShapeKeys.DESCRIPTION]: "Implement AI-driven supply chain management system for global operations",
    [IssueShapeKeys.START_DATE]: new Date("2024-04-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-04-30"),
    [IssueShapeKeys.PROGRESS]: 30,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Fulfillment",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "55",
    [IssueShapeKeys.NAME]: "Employee Training Platform",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Launch comprehensive online learning platform for employee development",
    [IssueShapeKeys.START_DATE]: new Date("2024-05-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-05-31"),
    [IssueShapeKeys.PROGRESS]: 100,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Function",
    [IssueShapeKeys.PRIORITY]: "Low"
  },
  {
    [IssueShapeKeys.ID]: "56",
    [IssueShapeKeys.NAME]: "Data Security Enhancement",
    [IssueShapeKeys.STATUS]: "High Risks",
    [IssueShapeKeys.DESCRIPTION]: "Upgrade security infrastructure with advanced encryption and monitoring",
    [IssueShapeKeys.START_DATE]: new Date("2024-06-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-06-30"),
    [IssueShapeKeys.PROGRESS]: 75,
    [IssueShapeKeys.CATEGORY]: "Evolving Cyber Threats",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "Low"
  },
  {
    [IssueShapeKeys.ID]: "57",
    [IssueShapeKeys.NAME]: "Retail Store Digitalization",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Implement digital solutions in physical retail locations",
    [IssueShapeKeys.START_DATE]: new Date("2024-07-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-07-31"),
    [IssueShapeKeys.PROGRESS]: 100,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Retail",
    [IssueShapeKeys.PRIORITY]: "Low"
  },
  {
    [IssueShapeKeys.ID]: "58",
    [IssueShapeKeys.NAME]: "E-commerce Platform Upgrade",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Enhance online shopping experience with new features and improved performance",
    [IssueShapeKeys.START_DATE]: new Date("2024-08-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-08-31"),
    [IssueShapeKeys.PROGRESS]: 60,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "E-com",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "59",
    [IssueShapeKeys.NAME]: "Brand Identity Refresh",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Update brand guidelines and visual identity across all channels",
    [IssueShapeKeys.START_DATE]: new Date("2024-09-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-09-30"),
    [IssueShapeKeys.PROGRESS]: 25,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Brand Marketing",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "60",
    [IssueShapeKeys.NAME]: "Corporate Social Responsibility",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Launch new CSR initiatives focused on community development",
    [IssueShapeKeys.START_DATE]: new Date("2024-10-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-10-31"),
    [IssueShapeKeys.PROGRESS]: 40,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Corporate",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "61",
    [IssueShapeKeys.NAME]: "Product Innovation Lab",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Establish dedicated space for product research and development",
    [IssueShapeKeys.START_DATE]: new Date("2024-11-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-11-30"),
    [IssueShapeKeys.PROGRESS]: 10,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Product",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "62",
    [IssueShapeKeys.NAME]: "Customer Analytics Platform",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Develop advanced analytics system for customer behavior insights",
    [IssueShapeKeys.START_DATE]: new Date("2024-12-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-12-31"),
    [IssueShapeKeys.PROGRESS]: 55,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "63",
    [IssueShapeKeys.NAME]: "Global Market Expansion",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Develop strategy for entering new international markets",
    [IssueShapeKeys.START_DATE]: new Date("2025-01-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-01-31"),
    [IssueShapeKeys.PROGRESS]: 20,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Corporate",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "64",
    [IssueShapeKeys.NAME]: "Smart Inventory System",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Implement AI-powered inventory management system",
    [IssueShapeKeys.START_DATE]: new Date("2025-02-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-02-28"),
    [IssueShapeKeys.PROGRESS]: 70,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Fulfillment",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "65",
    [IssueShapeKeys.NAME]: "Digital Marketing Campaign",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Launch comprehensive digital marketing strategy",
    [IssueShapeKeys.START_DATE]: new Date("2025-03-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-03-31"),
    [IssueShapeKeys.PROGRESS]: 35,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Brand Marketing",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "66",
    [IssueShapeKeys.NAME]: "Employee Wellness Program",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Implement comprehensive employee wellness initiatives",
    [IssueShapeKeys.START_DATE]: new Date("2025-04-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-04-30"),
    [IssueShapeKeys.PROGRESS]: 45,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Function",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "67",
    [IssueShapeKeys.NAME]: "Store Experience Redesign",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Redesign physical store layout and customer experience",
    [IssueShapeKeys.START_DATE]: new Date("2025-05-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-05-31"),
    [IssueShapeKeys.PROGRESS]: 100,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Retail",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "68",
    [IssueShapeKeys.NAME]: "Cloud Infrastructure Migration",
    [IssueShapeKeys.STATUS]: "High Risks",
    [IssueShapeKeys.DESCRIPTION]: "Migrate legacy systems to cloud-based infrastructure",
    [IssueShapeKeys.START_DATE]: new Date("2025-06-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-06-30"),
    [IssueShapeKeys.PROGRESS]: 60,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "69",
    [IssueShapeKeys.NAME]: "Product Quality Enhancement",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Implement new quality control measures across product lines",
    [IssueShapeKeys.START_DATE]: new Date("2025-07-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-07-31"),
    [IssueShapeKeys.PROGRESS]: 25,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Product",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "70",
    [IssueShapeKeys.NAME]: "E-commerce Analytics Dashboard",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Develop real-time analytics dashboard for e-commerce operations",
    [IssueShapeKeys.START_DATE]: new Date("2025-08-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-08-31"),
    [IssueShapeKeys.PROGRESS]: 50,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "E-com",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "71",
    [IssueShapeKeys.NAME]: "Corporate Sustainability Goals",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Set and implement new corporate sustainability targets",
    [IssueShapeKeys.START_DATE]: new Date("2025-09-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-09-30"),
    [IssueShapeKeys.PROGRESS]: 30,
    [IssueShapeKeys.CATEGORY]: "Advance Capabilities",
    [IssueShapeKeys.TEAM]: "Corporate",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "72",
    [IssueShapeKeys.NAME]: "Employee Training Program",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Launch new employee training and development program",
    [IssueShapeKeys.START_DATE]: new Date("2025-10-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-10-31"),
    [IssueShapeKeys.PROGRESS]: 40,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Function",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "73",
    [IssueShapeKeys.NAME]: "Retail Technology Integration",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Integrate new technologies into retail operations",
    [IssueShapeKeys.START_DATE]: new Date("2025-11-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-11-30"),
    [IssueShapeKeys.PROGRESS]: 20,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Retail",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "74",
    [IssueShapeKeys.NAME]: "Brand Awareness Campaign",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Launch global brand awareness campaign",
    [IssueShapeKeys.START_DATE]: new Date("2025-12-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-12-31"),
    [IssueShapeKeys.PROGRESS]: 35,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Brand Marketing",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "75",
    [IssueShapeKeys.NAME]: "Supply Chain Visibility",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Implement end-to-end supply chain visibility platform",
    [IssueShapeKeys.START_DATE]: new Date("2024-01-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-01-31"),
    [IssueShapeKeys.PROGRESS]: 25,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Fulfillment",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "76",
    [IssueShapeKeys.NAME]: "AI Product Recommendations",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Develop AI-powered product recommendation engine",
    [IssueShapeKeys.START_DATE]: new Date("2024-02-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-02-29"),
    [IssueShapeKeys.PROGRESS]: 55,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "77",
    [IssueShapeKeys.NAME]: "Store Performance Metrics",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Implement comprehensive store performance tracking system",
    [IssueShapeKeys.START_DATE]: new Date("2024-03-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-03-31"),
    [IssueShapeKeys.PROGRESS]: 30,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Retail",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "78",
    [IssueShapeKeys.NAME]: "E-commerce Mobile App",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Develop new mobile shopping application",
    [IssueShapeKeys.START_DATE]: new Date("2024-04-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-04-30"),
    [IssueShapeKeys.PROGRESS]: 65,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "E-com",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "79",
    [IssueShapeKeys.NAME]: "Brand Voice Guidelines",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Create comprehensive brand voice and tone guidelines",
    [IssueShapeKeys.START_DATE]: new Date("2024-05-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-05-31"),
    [IssueShapeKeys.PROGRESS]: 40,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Brand Marketing",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "80",
    [IssueShapeKeys.NAME]: "Corporate Ethics Program",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Develop and implement corporate ethics training program",
    [IssueShapeKeys.START_DATE]: new Date("2024-06-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-06-30"),
    [IssueShapeKeys.PROGRESS]: 45,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Corporate",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "81",
    [IssueShapeKeys.NAME]: "Product Design System",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Create unified product design system",
    [IssueShapeKeys.START_DATE]: new Date("2024-07-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-07-31"),
    [IssueShapeKeys.PROGRESS]: 35,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Product",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "82",
    [IssueShapeKeys.NAME]: "HR Management System",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Implement new HR management platform",
    [IssueShapeKeys.START_DATE]: new Date("2024-08-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-08-31"),
    [IssueShapeKeys.PROGRESS]: 60,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Function",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "83",
    [IssueShapeKeys.NAME]: "Retail Analytics Dashboard",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Develop comprehensive retail analytics dashboard",
    [IssueShapeKeys.START_DATE]: new Date("2024-09-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-09-30"),
    [IssueShapeKeys.PROGRESS]: 25,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Retail",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "84",
    [IssueShapeKeys.NAME]: "Cloud Security Framework",
    [IssueShapeKeys.STATUS]: "High Risks",
    [IssueShapeKeys.DESCRIPTION]: "Implement cloud security best practices",
    [IssueShapeKeys.START_DATE]: new Date("2024-10-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-10-31"),
    [IssueShapeKeys.PROGRESS]: 70,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "85",
    [IssueShapeKeys.NAME]: "E-commerce Checkout Optimization",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Optimize online checkout process",
    [IssueShapeKeys.START_DATE]: new Date("2024-11-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-11-30"),
    [IssueShapeKeys.PROGRESS]: 30,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "E-com",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "86",
    [IssueShapeKeys.NAME]: "Brand Content Strategy",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Develop comprehensive content strategy",
    [IssueShapeKeys.START_DATE]: new Date("2024-12-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-12-31"),
    [IssueShapeKeys.PROGRESS]: 50,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Brand Marketing",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "87",
    [IssueShapeKeys.NAME]: "Corporate Risk Management",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Implement enterprise risk management framework",
    [IssueShapeKeys.START_DATE]: new Date("2025-01-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-01-31"),
    [IssueShapeKeys.PROGRESS]: 35,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Corporate",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "88",
    [IssueShapeKeys.NAME]: "Product Quality Assurance",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Enhance product quality assurance processes",
    [IssueShapeKeys.START_DATE]: new Date("2025-02-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-02-28"),
    [IssueShapeKeys.PROGRESS]: 55,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Product",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "89",
    [IssueShapeKeys.NAME]: "Employee Performance System",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Implement new performance management system",
    [IssueShapeKeys.START_DATE]: new Date("2025-03-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-03-31"),
    [IssueShapeKeys.PROGRESS]: 40,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Function",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "90",
    [IssueShapeKeys.NAME]: "Store Operations Platform",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Develop comprehensive store operations platform",
    [IssueShapeKeys.START_DATE]: new Date("2025-04-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-04-30"),
    [IssueShapeKeys.PROGRESS]: 65,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Retail",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "91",
    [IssueShapeKeys.NAME]: "API Security Enhancement",
    [IssueShapeKeys.STATUS]: "High Risks",
    [IssueShapeKeys.DESCRIPTION]: "Implement advanced API security measures",
    [IssueShapeKeys.START_DATE]: new Date("2025-05-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-05-31"),
    [IssueShapeKeys.PROGRESS]: 45,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "92",
    [IssueShapeKeys.NAME]: "E-commerce Search Optimization",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Enhance product search functionality",
    [IssueShapeKeys.START_DATE]: new Date("2025-06-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-06-30"),
    [IssueShapeKeys.PROGRESS]: 50,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "E-com",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "93",
    [IssueShapeKeys.NAME]: "Brand Experience Platform",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Develop unified brand experience platform",
    [IssueShapeKeys.START_DATE]: new Date("2025-07-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-07-31"),
    [IssueShapeKeys.PROGRESS]: 30,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Brand Marketing",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "94",
    [IssueShapeKeys.NAME]: "Corporate Compliance System",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Implement comprehensive compliance management system",
    [IssueShapeKeys.START_DATE]: new Date("2025-08-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-08-31"),
    [IssueShapeKeys.PROGRESS]: 60,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Corporate",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "95",
    [IssueShapeKeys.NAME]: "Product Innovation Process",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Develop structured product innovation framework",
    [IssueShapeKeys.START_DATE]: new Date("2025-09-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-09-30"),
    [IssueShapeKeys.PROGRESS]: 35,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Product",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "96",
    [IssueShapeKeys.NAME]: "HR Analytics Platform",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Implement HR analytics and reporting system",
    [IssueShapeKeys.START_DATE]: new Date("2025-10-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-10-31"),
    [IssueShapeKeys.PROGRESS]: 55,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Function",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "97",
    [IssueShapeKeys.NAME]: "Retail Customer Insights",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Develop customer insights platform for retail",
    [IssueShapeKeys.START_DATE]: new Date("2025-11-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-11-30"),
    [IssueShapeKeys.PROGRESS]: 40,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Retail",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "98",
    [IssueShapeKeys.NAME]: "Cloud Migration Strategy",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Develop comprehensive cloud migration plan",
    [IssueShapeKeys.START_DATE]: new Date("2025-12-01"),
    [IssueShapeKeys.END_DATE]: new Date("2025-12-31"),
    [IssueShapeKeys.PROGRESS]: 45,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Tech",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "99",
    [IssueShapeKeys.NAME]: "E-commerce Payment System",
    [IssueShapeKeys.STATUS]: "Not Yet Started",
    [IssueShapeKeys.DESCRIPTION]: "Implement new payment processing system",
    [IssueShapeKeys.START_DATE]: new Date("2024-01-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-01-31"),
    [IssueShapeKeys.PROGRESS]: 30,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "E-com",
    [IssueShapeKeys.PRIORITY]: "Medium"
  },
  {
    [IssueShapeKeys.ID]: "100",
    [IssueShapeKeys.NAME]: "Brand Strategy Refresh",
    [IssueShapeKeys.STATUS]: "On Track",
    [IssueShapeKeys.DESCRIPTION]: "Update and implement new brand strategy",
    [IssueShapeKeys.START_DATE]: new Date("2024-02-01"),
    [IssueShapeKeys.END_DATE]: new Date("2024-02-29"),
    [IssueShapeKeys.PROGRESS]: 50,
    [IssueShapeKeys.CATEGORY]: "Advance Solutions",
    [IssueShapeKeys.TEAM]: "Brand Marketing",
    [IssueShapeKeys.PRIORITY]: "Medium"
  }
]; 